version: '3.6'

services:

  django:
    build: ./app/
    environment:
      # - SECRET_KEY=django
      - DATABASE_NAME=mikael
      - DATABASE_USER=mikael
      - DATABASE_PASSWORD=vrnovOYPDWm12
      - DATABASE_HOST=food-fact.clevaxcctwd5.us-east-1.rds.amazonaws.com
      - DATABASE_PORT=5432
      - DATABASE_URL=postgis://mikael:vrnovOYPDWm12@food-fact.clevaxcctwd5.us-east-1.rds.amazonaws.com:5432/food-fact
    volumes:
      - .:/app/p8_pure_beurre
      - static_volume:/app/staticfiles
      - media_volume:/app/public/media
    command: bash -c "python3 manage.py migrate && gunicorn --bind=0.0.0.0:8000 app.wsgi:application"
    restart: on-failure
    networks:
      - nginx_network

  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/public/media
    restart: on-failure
    depends_on:
      - django
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume: